name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths: ./apis/poi/**
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.0
    - name: Test
      run: dotnet test ./apis/poi/tests/UnitTests --verbosity normal
