name: POI API Build/Package

on:
  workflow_dispatch:
  push:
    paths: apis/poi/**
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     
    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build ./apis/poi/web -t openhackiaw3kcz1acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
  
    - name: Starting  Staging Slot
      run: az webapp start --name openhackiaw3kcz1poi --slot staging --resource-group openhackiaw3kcz1rg 
  
    - name: Deploying container to app service
      run: az webapp config container set --name openhackiaw3kcz1poi --slot staging --resource-group openhackiaw3kcz1rg --docker-custom-image-name openhackiaw3kcz1acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}  --docker-registry-server-url https://openhackiaw3kcz1acr.azurecr.io

  
 #   - uses: azure/webapps-deploy@v2
 #     with:
 #       app-name: 'openhackiaw3kcz1poi'
 #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
 #       images: 'openhackiaw3kcz1acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'
 #       slot-name: staging
   
    - name: checking deploy status
      run: bash ./deployscripts/api-status-check.sh https://openhackiaw3kcz1poi-staging.azurewebsites.net/api/healthcheck/poi 'json_status="Healthy"' 
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: OpenHack-DevOps-Morning-Avengers/MyDriving
        event-type: swapslots
        client-payload: '{"app": "openhackiaw3kcz1poi", "rg" : "openhackiaw3kcz1rg"}'
    
    
    - name: Checking workflow status
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "POI DotNet workflow failed."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
