name: POI API Build/Test/Package

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths: ./apis/poi/**
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Test
      run: dotnet test ./apis/poi/tests/UnitTests --verbosity normal
      
    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build ./apis/poi/web -t openhackiaw3kcz1acr.azurecr.io/appdb:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/appdb:${{ github.sha }}
        
    - name: Checking workflow status
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "User-Java CI worflow failed."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
