name: Go

on:
  push:
    paths: 
    - "./apis/trips"
    branches: [ develop ]

jobs:

  build:
    env:
      working-directory: ./apis/trips
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
