name: Trips API

on:
  workflow_dispatch:
  push:
    paths: apis/trips/**
    branches: [ develop ]
  pull_request:
    paths: apis/trips/**
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips/
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        

    - name: Build
      run: go build -mod=mod -v ./...

    - name: Test
      run: go test ./tripsgo/... -run Unit
#       run: go test -v ./...

    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build ./apis/poi/web -t openhackiaw3kcz1acr.azurecr.io/appdb:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}

    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

          
