name: Go

on:
  workflow_dispatch:
  push:
    paths: apis/trips/**
    branches: [ develop ]
  pull_request:
    paths: apis/trips/**
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips/
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        

    - name: Build
      run: go build -mod=mod -v .

    - name: Test
#       run: go test ./tripsgo -run Unit
      run: go test -v ./...
      
  
    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title {{ env.GITHUB_WORKFLOW }} --body "Here are more details."
      

          
