name: UserProfile Build/Package API

on:
  workflow_dispatch:
  push:
    paths: apis/userprofile/**
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/userprofile/
    steps:
    - uses: actions/checkout@v2
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build . -t openhackiaw3kcz1acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_number }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_number }} 
       
    - name: Deploying container to app service
      run: az webapp config container set --name openhackiaw3kcz1userprofile --slot staging --resource-group openhackiaw3kcz1rg --docker-custom-image-name openhackiaw3kcz1acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_number }}  --docker-registry-server-url https://openhackiaw3kcz1acr.azurecr.io

   # - name: Swap Staging to Prod
   #   run: |
   #     az webapp deployment slot swap -g openhackiaw3kcz1rg -n openhackiaw3kcz1userprofile --slot staging --target-slot production   
   
    - name: checking deploy status
      run: bash ../../deployscripts/api-status-check.sh https://openhackiaw3kcz1userprofile-staging.azurewebsites.net/api/healthcheck/user 'json_status="healthy"' 
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: OpenHack-DevOps-Morning-Avengers/MyDriving
        event-type: swapslots
        client-payload: '{"app": "openhackiaw3kcz1userprofile", "rg" : "openhackiaw3kcz1rg"}' 
        
    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_number }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
