name: UserProfile Test/Package API

on:
  workflow_dispatch:

  pull_request:
    paths: apis/userprofile/**
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/userprofile/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: npm ci
    - run: npm run build --if-present
    - run: npm test        
    
    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
