name: UserProfile API

on:
  workflow_dispatch:
  push:
    paths: apis/userprofile/**
    branches: [ develop ]
  pull_request:
    paths: apis/userprofile/**
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/userprofile/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: npm ci
    - run: npm run build --if-present
    - run: npm test        

    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build . -t openhackiaw3kcz1acr.azurecr.io/appdb:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}
    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
