name: Trips API Build

on:
  workflow_dispatch:
  push:
    paths: apis/trips/**
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips/
    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build . -t openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackiaw3kcz1poi'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}'
        slot-name: staging

    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

          
