name: Trips API Build

on:
  workflow_dispatch:
  push:
    paths: apis/trips/**
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips/
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - run: | 
        docker build . -t openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }} 
        docker push openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}

        
    - name: Deploying container to app service
      run: az webapp config container set --name openhackiaw3kcz1trips --slot staging --resource-group openhackiaw3kcz1rg --docker-custom-image-name openhackiaw3kcz1acr.azurecr.io/devopsoh/api-trips:${{ github.sha }}  --docker-registry-server-url https://openhackiaw3kcz1acr.azurecr.io

    - name: checking deploy status
      run: bash ./deployscripts/api-status-check.sh https://openhackiaw3kcz1trips-staging.azurewebsites.net/api/healthcheck/trips '"status":"healthy"' 
      env:
        working-directory: .

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: OpenHack-DevOps-Morning-Avengers/MyDriving
        event-type: swapslots
        client-payload: '{"app": "openhackiaw3kcz1trips", "rg" : "openhackiaw3kcz1rg"}'


    - name: The job has failed
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "Here are more details."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

          
