# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: User-Java API (main branch) deploy (CD)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
    - 'apis/user-java/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1 
      with: 
        login-server: openhackiaw3kcz1acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }} 
       
    - name: Build docker container 
      run: docker build ./apis/user-java/ -t openhackiaw3kcz1acr.azurecr.io/api-user-java:${{ github.sha }}
    
    - name: Pushing container image to ACR
      run: docker push openhackiaw3kcz1acr.azurecr.io/api-user-java:${{ github.sha }}

    - name: list all web app available
      run: az webapp list -o table

    - name: Deploying container to app service
      run: az webapp config container set --name openhackiaw3kcz1userjava --slot staging --resource-group openhackiaw3kcz1rg --docker-custom-image-name openhackiaw3kcz1acr.azurecr.io/api-user-java:${{ github.sha }}  --docker-registry-server-url https://openhackiaw3kcz1acr.azurecr.io

    - name: checking deploy status
      run: |
        echo "Checking api health"
        ./deployscripts/api-status-check.sh https://openhackiaw3kcz1userjava-staging.azurewebsites.net/api/healthcheck/user-java 'json_status="healthy"' 
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: OpenHack-DevOps-Morning-Avengers/MyDriving
        event-type: swapslots
        client-payload: '{"app": "openhackiaw3kcz1userjava", "rg" : "openhackiaw3kcz1rg"}'
        
    - name: Checking workflow status
      if: ${{ failure() }}
      run: gh issue create --title "${{ github.workflow }}-${{ github.run_id }}" --body "User-Java CD worflow failed."
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

